---
- name: Install Apache Web Server on AMI Linux. Upload web page example
  hosts: all
  remote_user: root
  become: yes
  become_user: root
  become_method: sudo
 

  vars:
    source_dir: /home/ubuntu/git/DevOps_online_Dnipro_2020Q3Q4/html
    destin_dir: /var/www


  tasks:

  - name: Check Linux distro
    debug: var=ansible_os_family

  - block: # For RedHat
  
    - name: Install Apache Web Server on RedHat Family
      yum: name=httpd state=latest
     
    - name: Start Apache and enable it during boot
      service: name=httpd state=started enabled=yes
  
    when: ansible_os_family == "RedHat"
  
  - block: #For Debian

    - name: Install Apache Web Server on Debian Family
      apt:  update_cache=yes name=apache2 state=latest

    - name: Start Apache and enable it during boot
      service: name=apache2 state=started enabled=yes

    when: ansible_os_family == "Debian"

  - name: Copy dir "html" to target Debian and Red Hat servers
    copy: src={{ source_dir }}/.  dest={{ destin_dir }} 
    ignore_errors: True
    async: 60
    poll: 60
